name: aspirehire
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  percent_indicator: ^4.2.3
  shared_preferences: ^2.2.2
  flutter_bloc: ^8.1.6  # Downgraded for compatibility
  equatable: ^2.0.5
  dio: ^5.4.2+1
  cupertino_icons: ^1.0.6
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  file_picker: ^9.0.1
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


flutter:
  assets:
    - assets/
  uses-material-design: true
